language: ruby

script: rake halo
deploy:
  provider: releases
  api_key: $API_KEY_GENERAL
  file: "in.dist"
  skip_cleanup: true
  on:
    tags: true

env:
  API_KEY_GENERAL: "${{ secrets.SPOOLER_TOKEN }}"