language: ruby

script: rake halo
deploy:
  provider: releases
  github_token: $TOKEN_GENERAL
  file: "in.dist"
  skip_cleanup: true
  on:
    tags: true

env:
  TOKEN_GENERAL: "${{ secrets.SPOOLER_TOKEN }}"